### ISSUE TITLE
name suggestions

### ISSUE THREAD

**Issue by soenkekluth** [developit/greenlet#3] opened 2018-01-27 10:36 UTC
like you said. the name isn't that meaningful ;) 

these are also available:
threadit
threadd
workk
workthread

where my favourite is threadit

**Comment by soenkekluth** [comment] 2018-01-27 10:37
parallize

**Comment by mariuslundgard** [comment] 2018-01-27 16:56
coworker (co as in coroutine)

**Comment by sergeysova** [comment] 2018-01-27 21:52
awaitme
unthread
letthread
workthread

**Comment by sqbing** [comment] 2018-01-29 01:15
I bet I'm not the first one mentioned Gevent in Python. It also uses greenlet.
I spent some time on projects based on Gevent. So maybe it's a bit confused here.
Anyway your good tool. :)

**Comment by mefjuu** [comment] 2018-01-29 12:05
parallizator

**Comment by dzek69** [comment] 2018-01-29 13:11
I may be weird but I like greenlet.

Using technical keywords as name isn't mandatory for a library to be successful or whatever you could think new name would make better.

**Comment by developit** [comment] 2018-01-29 15:42
I really like `coworker`. Hey @JoyKrishnaMondal - any chance you'd be willing to donate the npm package name?

FWIW it's probably too late to change the name at this point anyway, though I might be tempted purely based on coworker being too awesome to pass up.

**Comment by harsh-ashtekar** [comment] 2018-02-01 00:38
ThreadyMcThreadface?

**Comment by mariuslundgard** [comment] 2018-02-01 06:50
workit!

(edit: doh, that’s already an active package)

**Comment by Ima8** [comment] 2018-02-01 16:39
fly.js

**Comment by sourcevault** [comment] 2018-02-01 20:54
How about sharing the name ?

I will use `coworker/most`
and other ppl could use 
`coworker/foobar` ?

**Comment by sourcevault** [comment] 2018-02-01 20:55
How about sharing the name ?

I will use `coworker/most`
and other ppl could use
`coworker/foobar` ?

@briancavalier

**Comment by sergeysova** [comment] 2018-02-01 21:45
@sourcevault maybe npm-scopes?

eg.: `@username/coworker`

**Comment by sourcevault** [comment] 2018-02-02 00:55
`co-worker` is also available ( fingers crossed someone does not claim it )  

`<xyz>worker` also sounds good

**Comment by sergeysova** [comment] 2018-02-02 01:04
`aworker`

**Comment by sourcevault** [comment] 2018-02-02 06:55
After thinking about this a little more deeply I think I can pinpoint what the problem is and also think I have a solution that will work for all parties.

So the problem we have over here is similar to the prisoner's dilemma ( and I am going to use it to 
model my solution )

- its zero sum in nature, whoever pushes code to coworker for reasons outside my control gets an inherit I am going to stay marketing advantage ?

-  other options `aworker` , `co-worker` is not satisfactory - since for example people are going to confuse `coworker` with `co-worker`  (as I said zero sum )

In a situation like this we could nullify the marketing advantage by making it not available for anyone to control - just like with public parks , international waters, etc.

How this works in practice is that `coworker` is an object and u would need to import 

```
{greenlet} = require ("coworker")
```
or in my case :

```
{foobar} = require ("coworker")
```
and we leave coworker itself just a proxy - this way everyone is able to take advantage of the marketing value. 

**ALTERNATE BETTER TECHNIQUE**

Its better to publish `greenlet` on : 

`npm install coworker/{x}`

What I am going to do is when any user `npm install coworker`:

It just shows an error message and points to all repos in `coworker/{x}`

This way : 

- Each repo is independent and under control of the original author.

- Its also fair to future programmers who want to take a stab at trying to experiment with web worker API, they are able to compete freely without marketing concerns.

- Its in the interest of current web-worker API authors to allow future programmers to publish under `coworker/{x}` since due to network effects each API`s mindshare would feed off each other. 

- I only have to push code once to show the error message and there is no issue of code breakage, rouge actor etc. If for some reason my account gets hacked and someone pushes malicious code on `coworker` it wont break any `coworker/{x}`

@developit 


SIDENOTE : The reason I have been on a coding haitus is due to personal medical circumstances.  I have severe RSI that I am trying to recover from so you can imagine it took great pain for me to type this message out - I hope no one minds my late replies, its not that I am ignoring anyone - its just that its literally impossible for me to type a message without hurting my fingers - so I have to weight the importance of the message against pain that I have to endure.

**Comment by briancavalier** [comment] 2018-02-02 12:25
@sourcevault Thanks for tagging me so I could out about this cool project :+1:

**Comment by sergeysova** [comment] 2018-02-02 19:38
@sourcevault 
> Its better to publish greenlet on:
> npm install coworker/{x}

When you run `npm install foo/bar` npm search npm package in github.com/foo/bar

Npm does not allow packages with `/` in it name.

But npm has "at" scopes to publish under user's private scope. For example: `@username/package-name`

**Comment by sourcevault** [comment] 2018-02-02 19:47
oh sorry - i meant `coworker.{x}`

so it would be `coworker.greenlit`

the original coworker could just be an automatic error script or something that pull from all the repos.

I think for greenlit it could be really cool like this : 

`coworker.async`

**Comment by jimthedev** [comment] 2018-02-10 17:46
offthread

**Comment by jimthedev** [comment] 2018-02-10 17:49
twork
workoff

**Comment by jimthedev** [comment] 2018-02-10 17:50
krow (work backwards)

**Comment by styfle** [comment] 2018-05-13 13:56
greenlet = require(‘let-my-body-do-the-work’)

Get it? 😏

**Comment by developit** [comment] 2018-05-15 12:22
@sourcevault Thanks for the explanation, but I don't have any interest in sharing a package name TBH - it would be a nightmare for bundlers and just isn't worth the trouble.

I'm going to close this issue out - I don't think the name of this library is worth changing at this point, its too widely referenced.

**Closed as completed by developit** 2018-05-15 12:22 UTC
Labels: discussion
